#!/usr/bin/env bash
#This script displays information about subdomains
# shellcheck disable=SC2086

parseParam()
{
    awk '/ANSWER SECTION:/{getline; split($1,array,"."); print "The subdomain", array[1], "is a", $4, "record and points to", $NF}'
}

if [ $# -eq 1 ]; then
    dns="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
    dns="$2.$1"
fi

dig $dns | parseParam $1