#!/usr/bin/env bash
# Install nginx and creates redirection
sudo apt-get update -y
sudo apt-get install -y nginx
sudo sed -i '/listen \[::]:80 default_server;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart