#!/usr/bin/env bash
#custom 404 page.

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen \[::]:80 default_server;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

sudo service nginx restart

