#!/usr/bin/env bash
# Install and configure HAproxy .
apt-get -y install haproxy

# edit config file
server_config=\
"
        bind *:80
        mode http   
        balance roundrobin
        server 335-web-01 3.81.227.144:80 check
        server 335-web-02 3.91.56.29:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
