#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
for _ in {1..10}
# _ is a standard placeholder name for ignored members in a for-loop and tuple assignment
do
	echo "Holberton School"
done
